### PR TITLE
reworks how threads work again

### PR DESCRIPTION
**Pull request by jupyterkat**
there can now be only one rayon task spawn running at all times
makes it so SSair must pause when threads are running with condvars
threads are now started by a message across a flume channel

### CODE REVIEW

**Comment by jupyterkat** [comment]
gotta clean up that history

**Comment by Putnam3145** [comment]
i can just squash merge

**Comment by jupyterkat** [comment]
the condvar is completely unnecessary when It’s paused on the entire thread like this I realized

**Comment by jupyterkat** [comment]
unless I make it just pause on katmos

**Pull request closed without merging**
